### ISSUE TITLE
Feature: Dynamic Interval receives elapsedTime

### ISSUE THREAD

**Issue by ScottONeal** [DonutEspresso/reissue#4]
It would be nice if the dynamic interval function could received the elapsed time from the last `execute()`. 

``` js
var handler = reissue.create({
    func: function print(callback) {
        console.log('hi');
        return callback();
    },
    interval: function(elapsedTime) {
        if ( elapsedTime > someThreshold ) } 
            console.log('long execution time from reissue'); 
            return 2000;
        else {
             return 1000;
         }
     }
});
```

However, this might have logical conflicts with: https://github.com/DonutEspresso/reissue/blob/master/lib/index.js#L145

**Comment by DonutEspresso** [comment]
Apologies, somehow this slipped through my radar and I didn't get a notification!

This seems like a pretty reasonable thing to support - that is, if you provide an interval function, to always prefer the return value regardless of last elapsed time. If the function returns 0/-1, then invoke immediately. Thoughts?
